# Generated by Django 5.2.10 on 2026-01-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_servicecategory_serviceplan_servicesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('flat', 'Flat Amount'), ('percent', 'Percentage')], default='flat', max_length=10)),
                ('discount_value', models.PositiveIntegerField(default=0)),
                ('min_order_amount', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
