# Generated by Django 5.2.4 on 2025-11-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='project_link',
            field=models.URLField(blank=True, help_text='Optional: link to live site or demo', null=True),
        ),
    ]
