# Generated by Django 5.2.4 on 2025-11-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_portfolioitem_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
