# Generated by Django 5.2.4 on 2025-11-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(help_text='Include country code, e.g. +919219317352', max_length=30)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('website_type', models.CharField(choices=[('blog', 'Blog Website'), ('business', 'Business/Company'), ('ecommerce', 'E-commerce'), ('portfolio', 'Portfolio/Personal'), ('lms', 'LMS / Course'), ('news', 'News / Magazine'), ('custom', 'Custom Requirement')], max_length=20)),
                ('support_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('hinglish', 'Hinglish'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
