# Generated by Django 5.2.4 on 2025-11-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='country_code',
            field=models.CharField(blank=True, default='+91', help_text='E.164 country code like +91, +1, +44', max_length=6),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='full_phone',
            field=models.CharField(blank=True, default='', editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Local number (without country code)', max_length=30),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='support_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('hi', 'Hindi'), ('hinglish', 'Hinglish'), ('other', 'Other')], max_length=20),
        ),
    ]
