# Generated by Django 5.2.4 on 2025-11-10 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contactmessage_country_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='support_language',
            field=models.CharField(blank=True, choices=[('hi', 'Hindi'), ('en', 'English'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('kn', 'Kannada'), ('ml', 'Malayalam')], max_length=20),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('country_code', models.CharField(blank=True, default='+91', max_length=6)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('state', models.CharField(blank=True, default='', max_length=80)),
                ('country', models.CharField(blank=True, default='', max_length=80)),
                ('pincode', models.CharField(blank=True, default='', max_length=12)),
                ('company', models.CharField(blank=True, default='', max_length=120)),
                ('tax_id', models.CharField(blank=True, default='', max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
