# Generated by Django 5.2.8 on 2026-01-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_homecta_homehero_homeportfolio_howwework_service_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='HomeService',
        ),
        migrations.DeleteModel(
            name='HomeCTA',
        ),
        migrations.DeleteModel(
            name='HomeHero',
        ),
        migrations.AlterModelOptions(
            name='homeportfolio',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='homeportfolio',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
