# Generated by Django 5.2.8 on 2026-01-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_service_homeservice_delete_homecta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeportfolio',
            options={'ordering': ['order'], 'verbose_name': 'Our Work Item', 'verbose_name_plural': 'Our Work'},
        ),
        migrations.AlterModelOptions(
            name='homeservice',
            options={'ordering': ['order'], 'verbose_name': 'Home Our Service', 'verbose_name_plural': 'Home Our Services'},
        ),
        migrations.AlterModelOptions(
            name='howwework',
            options={'ordering': ['step_number'], 'verbose_name': 'How We Work Step', 'verbose_name_plural': 'How We Work'},
        ),
        migrations.AlterModelOptions(
            name='whydevzuno',
            options={'ordering': ['order'], 'verbose_name': 'Why Devzuno Point', 'verbose_name_plural': 'Why Devzuno'},
        ),
        migrations.AddField(
            model_name='homeportfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/portfolio/'),
        ),
        migrations.AddField(
            model_name='homeservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/services/'),
        ),
        migrations.AddField(
            model_name='howwework',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/how/'),
        ),
        migrations.AddField(
            model_name='whydevzuno',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/why/'),
        ),
    ]
