# Generated by Django 5.2.10 on 2026-01-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_homeportfolio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingplan',
            options={'ordering': ['-highlight', 'price']},
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='delivery_time',
            field=models.CharField(default='2-3 Days', max_length=50),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='old_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='support',
            field=models.CharField(default='7 Days Free Support', max_length=100),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='features',
            field=models.TextField(help_text='Write one feature per line'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='price_text',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
