# Generated by Django 5.2.4 on 2025-11-11 19:24

import django.db.models.deletion
import support.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_ticket_options_ticket_attachment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('-updated_at', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ('created_at',)},
        ),
        migrations.RenameField(
            model_name='ticketmessage',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='ticketmessage',
            old_name='is_staff',
            new_name='is_staff_reply',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='message',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('answered', 'Answered'), ('closed', 'Closed')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=support.models.ticket_attachment_path),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.ticket'),
        ),
    ]
