# Generated by Django 5.2.4 on 2025-11-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_ticket_options_alter_ticketmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='tickets/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.CharField(choices=[('general', 'General'), ('billing', 'Billing'), ('technical', 'Technical'), ('sales', 'Sales')], default='general', max_length=20),
        ),
    ]
