# Generated by Django 5.2.4 on 2025-11-11 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_ticket_options_ticket_attachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('-updated_at', '-created_at')},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.CharField(choices=[('general', 'General'), ('billing', 'Billing'), ('technical', 'Technical'), ('sales', 'Sales')], db_index=True, default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('answered', 'Answered'), ('closed', 'Closed')], db_index=True, default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='support_tic_status_363e60_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['department'], name='support_tic_departm_6ff088_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority'], name='support_tic_priorit_a48b90_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='support_tic_created_438cd5_idx'),
        ),
    ]
