# Generated by Django 5.2.8 on 2025-11-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Devzuno Technologies', max_length=120)),
                ('whatsapp', models.CharField(default='+919219317352', max_length=20)),
                ('support_email', models.EmailField(default='support@devzuno.com', max_length=254)),
                ('razorpay_mode', models.CharField(choices=[('demo', 'Demo'), ('live', 'Live')], default='demo', max_length=10)),
                ('razorpay_key_id', models.CharField(blank=True, default='', max_length=200)),
                ('razorpay_key_secret', models.CharField(blank=True, default='', max_length=200)),
                ('logo_text', models.CharField(default='Devzuno', max_length=60)),
                ('hero_title', models.CharField(default='Build, launch & manage your digital business', max_length=200)),
                ('hero_subtitle', models.CharField(default='Websites, apps, domains, invoices, tickets — all in one platform.', max_length=300)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
